version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: bremray
      POSTGRES_PASSWORD: devsecret
      POSTGRES_DB: bremray_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bremray"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: